### ISSUE TITLE
Geosnipe refusing to install?

### ISSUE THREAD

**Issue by mr-hespicable** [Geographs/GeoSnipe#14]
When i am trying to install Geosnipe, the .exe opens a cmd window, then shows this text
![image](https://user-images.githubusercontent.com/85052021/127751338-a5b421e4-7df9-473e-9013-d02012146dee.png)
for a brief second. When I run this command, it outputs
![image](https://user-images.githubusercontent.com/85052021/127751352-c2138206-886d-4c08-b990-3c5b7330298e.png)
I'm not really sure what to do here

**Comment by Geographs** [comment]
You have to run it in the command prompt.

```
cd (installation directory)
```

```
geosnipe (commands)
```
